language: python
python:
- "3.5"
install: "pip install -r requirements.txt"
services:
  - postgresql
before_script:
  - psql -c 'create database idiobot;' -U postgres
script: python -m tests.maintest
addons:
    code_climate:
        repo_token: 058c3e88739f04ae4ff0e0250434052b9fdc1c7ab6be3b21315b1a8db3ac233d